### ISSUE TITLE
NullPointerException when invoked by service-catalog 0.0.1

### ISSUE THREAD

**Issue by ljnelson** [microbean/microbean-service-broker-jaxrs#1]
When the Kubernetes service catalog, ancient and unsupported version 0.0.1, hits the `ServiceInstancesResource#deleteServiceInstance()` method, a `NullPointerException` results:

    SEVERE: java.lang.NullPointerException
    java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:203)
	at org.microbean.servicebroker.jaxrs.ServiceInstancesResource.deleteServiceInstance(ServiceInstancesResource.java:245)

This is probably valid in the sense that whatever is being asserted probably should NOT be `null`, but we need to make sure.

**Comment by ljnelson** [comment]
The line in question, 245, is this:

    Objects.requireNonNull(serviceId);

...where `serviceId` is a `@QueryParam`-annotated parameter.  So the ancient and unsupported version 0.0.1 of the Kubernetes service catalog is not passing the (required) `serviceId` parameter.
